on:
  push:
    paths:
      - "list.txt"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read list.txt and update README.md
        run: |
          CONTENT=$(<list.txt)
          TEMP_FILE=$(mktemp)

          {
            echo "<!-- BEGIN LIST CONTENT -->"
            echo '```text'
            echo "$CONTENT"
            echo '```'
            echo "<!-- END LIST CONTENT -->"
          } > "$TEMP_FILE"

          # Remove old block
          sed -i '/<!-- BEGIN LIST CONTENT -->/,/<!-- END LIST CONTENT -->/d' README.md
          
          # Insert new block before END marker
          sed -i "/<!-- END LIST CONTENT -->/e cat $TEMP_FILE" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet || git commit -m "Update README with latest list.txt content"
          git push

