name: Update README with TXT contents

on:
  push:
    paths:
      - "list.txt"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Update README
        run: |
          CONTENT=$(<example.txt)
          awk '/<!-- BEGIN TXT CONTENT -->/ {print; print "```text"; system("cat example.txt"); print "```"; skip=1; next} /<!-- END TXT CONTENT -->/ {skip=0} !skip' README.md > README.new.md
          mv README.new.md README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with latest example.txt content"
          git push
