name: Update README with Anime List

on:
  push:
    paths:
      - "list.txt"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read list.txt and update README.md
        run: |
          CONTENT=$(<list.txt)
          sed -i "/<!-- BEGIN LIST CONTENT -->/,+2d" README.md
          sed -i "/<!-- END LIST CONTENT -->/i <!-- BEGIN LIST CONTENT -->\n\`\`\`text\n$CONTENT\n\`\`\`\n<!-- END LIST CONTENT -->" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet || git commit -m "Update README with latest list.txt content"
          git push
